version: "3"

services:
  app:
    build:
      context: ./node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db
    restart: always
    tty: true
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgres
    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
